version: '3.2'

services:
  nginx:
    container_name: ng_nginx
    build: ./docker/nginx
    links:
      - movie
      - auth
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - "${APP_PORT:-5000}:80"

  movie:
    build: ./movie
    container_name: ng_movie
    volumes:
      - "./movie:/src/app"
    working_dir: "/src/app"
    links:
      - mysqldb
    ports:
      - "5000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
    command: npm run start

  auth:
    build: ./auth
    container_name: ng_auth
    volumes:
      - "./auth:/src/app"
    working_dir: "/src/app"
    ports:
      - "3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
    command: npm run start

  mysqldb:
    container_name: ng_mysqldb
    image: mysql:8.0
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--innodb_use_native_aio=0"
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/mysql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: netguru
      MYSQL_USER: netguru
      MYSQL_PASSWORD: netguru
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"